language: node_js
node_js:
  - "5.7.0"
script:
  - "cd sim && node ../node_modules/typescript/bin/tsc"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
cache:
  directories:
    - node_modules
    - built/cache

